//$file${controller::.::controller.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: controller.qm
// File:  ${controller::.::controller.c}
//
// This code has been generated by QM 6.2.0 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
//                    Q u a n t u m  L e a P s
//                    ------------------------
//                    Modern Embedded Software
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Please contact Quantum Leaps for commercial licensing options, which
// expressly supersede the GNU General Public License and are specifically
// designed for licensees interested in retaining the proprietary status
// of the generated code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${controller::.::controller.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpc.h"
#include "controller.h"

Q_DEFINE_THIS_FILE

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${controller::ControllerSignals} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${controller::ControllerSignals} ...........................................
enum ControllerSignals {
    TIMEOUT_SIG = Q_USER_SIG,
    MAX_SIG
};
//$enddef${controller::ControllerSignals} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${controller::controllerQueueSto[5]} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${controller::controllerQueueSto[5]} .......................................
static QEvt const * controllerQueueSto[5];
//$enddef${controller::controllerQueueSto[5]} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${controller::controllerStack[configMINIMAL_STACK_SIZE]} vvvvvvvvvvvv

//${controller::controllerStack[configMINIMAL_ST~} ...........................
static StackType_t controllerStack[configMINIMAL_STACK_SIZE];
//$enddef${controller::controllerStack[configMINIMAL_STACK_SIZE]} ^^^^^^^^^^^^

//$declare${controller::controller} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${controller::controller} ..................................................
typedef struct controller {
// protected:
    QActive super;

// public:

// private:
    QTimeEvt timeEvt;
} controller;

extern controller controller_instance;

// private:

#ifdef Q_SPY
static void controller_init_dictionary(controller * const me);
#endif // def Q_SPY

// protected:
static QState controller_initial(controller * const me, void const * const par);
static QState controller_LED_OFF(controller * const me, QEvt const * const e);
static QState controller_LED_ON(controller * const me, QEvt const * const e);
//$enddecl${controller::controller} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${controller::AO_controller} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${controller::AO_controller} ...............................................
QActive * AO_controller;
//$enddef${controller::AO_controller} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${controller::controller_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${controller::controller_ctor} .............................................
void controller_ctor(void) {
    controller * const me = &controller_instance;
    AO_controller = &(controller_instance.super);

    controller_init_dictionary(me);

    QActive_ctor(&me->super, Q_STATE_CAST(&controller_initial));
    QTimeEvt_ctorX(&me->timeEvt, &me->super, TIMEOUT_SIG, 0U);

    QActive_setAttr(AO_controller,
                    TASK_NAME_ATTR,
                    "Controller");
    QACTIVE_START(AO_controller,
                  (QPrioSpec)1,
                  controllerQueueSto,
                  Q_DIM(controllerQueueSto),
                  controllerStack,
                  Q_DIM(controllerStack),
                  (QEvt *)0);

}
//$enddef${controller::controller_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${controller::controller} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${controller::controller} ..................................................
controller controller_instance;

//${controller::controller::init_dictionary} .................................
#ifdef Q_SPY
static void controller_init_dictionary(controller * const me) {
    controller * instance = me;
    QS_OBJ_DICTIONARY(instance);

    QS_SIG_DICTIONARY(TIMEOUT_SIG, (void *)0);

    QS_FUN_DICTIONARY(&controller_LED_OFF);
    QS_FUN_DICTIONARY(&controller_LED_ON);
}
#endif // def Q_SPY

//${controller::controller::SM} ..............................................
static QState controller_initial(controller * const me, void const * const par) {
    //${controller::controller::SM::initial}
    EALLOW;
    SysCtrlRegs.PCLKCR3.bit.GPIOINENCLK = 1;
    GpioCtrlRegs.GPBPUD.bit.GPIO34 = 1;
    GpioCtrlRegs.GPBDIR.bit.GPIO34 = 1;
    GpioCtrlRegs.GPBMUX1.bit.GPIO34 = 0;
    EDIS;
    return Q_TRAN(&controller_LED_OFF);
}

//${controller::controller::SM::LED_OFF} .....................................
static QState controller_LED_OFF(controller * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${controller::controller::SM::LED_OFF}
        case Q_ENTRY_SIG: {
            QTimeEvt_armX(&me->timeEvt, 1800, 0U);
            GpioDataRegs.GPBSET.bit.GPIO34 = 1;
            status_ = Q_HANDLED();
            break;
        }
        //${controller::controller::SM::LED_OFF::TIMEOUT}
        case TIMEOUT_SIG: {
            status_ = Q_TRAN(&controller_LED_ON);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${controller::controller::SM::LED_ON} ......................................
static QState controller_LED_ON(controller * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${controller::controller::SM::LED_ON}
        case Q_ENTRY_SIG: {
            QTimeEvt_armX(&me->timeEvt, 200, 0U);
            GpioDataRegs.GPBCLEAR.bit.GPIO34 = 1;
            status_ = Q_HANDLED();
            break;
        }
        //${controller::controller::SM::LED_ON::TIMEOUT}
        case TIMEOUT_SIG: {
            status_ = Q_TRAN(&controller_LED_OFF);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
//$enddef${controller::controller} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

