//$file${controller::.::controller.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: controller.qm
// File:  ${controller::.::controller.h}
//
// This code has been generated by QM 6.2.0 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
//                    Q u a n t u m  L e a P s
//                    ------------------------
//                    Modern Embedded Software
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Please contact Quantum Leaps for commercial licensing options, which
// expressly supersede the GNU General Public License and are specifically
// designed for licensees interested in retaining the proprietary status
// of the generated code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${controller::.::controller.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef CONTROLLER_H
#define CONTROLLER_H

//$declare${controller::AO_controller} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${controller::AO_controller} ...............................................
extern QActive * AO_controller;
//$enddecl${controller::AO_controller} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$declare${controller::controller_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${controller::controller_ctor} .............................................
void controller_ctor(void);
//$enddecl${controller::controller_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#endif /* CONTROLLER_H */
